room.status.change.enable = true
booking.history.record.limit = 3
filetype.data.used = csv
view.type = console

db.driver = org.postgresql.Driver
db.url = jdbc:postgresql://db:5432/hotel_app
db.username = postgres
db.password = yura